---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wikijs-config
  namespace: wikijs
data:
  DB_HOST: {{env "DB_HOST"}}
  DB_PORT: {{env "DB_PORT"}}
  DB_NAME: {{env "DB_NAME"}}
  DB_USER: {{env "DB_USER"}}
  DB_TYPE: {{env "DB_TYPE"}}