---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wikijs-ingress
  namespace: wikijs
spec:
  rules:
  - host: wiki.darkleafygreens.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wikijs-svc
            port:
              number: 80
