---
apiVersion: v1
kind: Secret
metadata:
  name: wikijssecrets
  namespace: wikijs
data:
  DB_HOST: MTAuMC4wLjI0
  DB_NAME: d2lraWpzZGI=
  DB_USER: d2lraWpzZGJ1c2Vy
  DB_PORT: MzMwNg==
  DB_TYPE: bWFyaWFkYg==
  DB_PASSWORD: UGFzc3dvcmQ5OQ==

